x-common: &common
  build:
    context: .
    dockerfile: Dockerfile
  working_dir: /app
  gpus: all
  shm_size: "8gb"
  ipc: host
  environment:
    PYTHONHASHSEED: "42"
    CUBLAS_WORKSPACE_CONFIG: ":4096:8"
    OMP_NUM_THREADS: "1"
    MKL_NUM_THREADS: "1"
    NVIDIA_VISIBLE_DEVICES: "all"
    NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
  volumes:
    - ./data:/app/data
    - ./results:/app/results
    - ./logs:/app/logs
    - ./configs:/app/configs:ro
    - ./src:/app/src:ro
  restart: "no"

services:
  prepare_train_data:
    <<: *common
    container_name: bfs_2d_prepare_data
    command: python src/prepare_data.py --config configs/dataset_etl/prepare_data.yaml
  
  train_mlp:
    <<: *common
    container_name: bfs_2d_mlp_train
    command: python src/train_mlp.py --config configs/baseline/mlp_base.yaml

  train_pinn:
    <<: *common
    container_name: bfs_2d_pinn_train
    command: python src/train_pinn.py --config configs/baseline/pinn_cont_base.yaml

  train_pinn_cont_mom:
    <<: *common
    container_name: bfs_2d_pinn_train_cont_mom_v1
    command: python src/train_pinn.py --config configs/pinn_cont_mom_v1.yaml

  benchmark_mlp:
    <<: *common
    container_name: bfs_2d_mlp_benchmark
    command: python src/run_external_benchmark.py 
        --config configs/mlp_v3.yaml 
        --model-path results/models/mlp_v3_d4_w64.pt 
        --training-reynolds 32000
  
  benchmark_pinn:
    <<: *common
    container_name: bfs_2d_pinn_benchmark
    command: python src/run_external_benchmark.py 
      --config configs/pinn_cont_v3.yaml 
      --model-path results/models/pinn_cont_v3_d4_w64.pt 
      --training-reynolds 32000

  clean_experiments:
    <<: *common
    container_name: bfs_2d_cleanup
    command: python src/cleanup_experiments.py
    ## --apply --yes

  compare_experiments:
    <<: *common
    container_name: bfs_2d_compare_exp
    command: python src/compare_experiment_logs.py 
      --logs-root logs 
      --output-dir results/comparisons